"
Dialogs, sometimes called ""modals"", appear above the page and require the user's immediate attention.

By design, a dialog's height will never exceed that of the viewport. As such, dialogs will not scroll with the page ensuring the dialog header and footer are always accessible to the user.
"
Class {
	#name : #SlDialog,
	#superclass : #SlAbstractPrompter,
	#category : #'CodeParadise-WebApplication-Shoelace-Elements'
}
