Extension { #name : #Package }

{ #category : #'*CodeParadise-WebApplication-Debugger' }
Package >> codeParadiseWebApplicationDebuggerDevelopmentSupport [

	"Marker to indicate this package is a development support package"

	<developmentSupport>
]

{ #category : #'*CodeParadise-WebApplication-Debugger' }
Package >> codeParadiseWebApplicationShoelaceDevelopmentSupport [

	"Marker to indicate this package is a development support package
	(or more precise: Shoelace is used in the ViewInspector)"

	<developmentSupport>
]
